version: '3.7'
services:
  influxdb:
    image: influxdb:2.6
    container_name: influxdb2
    volumes:
      - ./ssl:/etc/ssl
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=ChangePassword
      - DOCKER_INFLUXDB_INIT_ORG=myocx
      - DOCKER_INFLUXDB_INIT_RETENTION=4w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=SecretTokenToChangeHereAndTelegrafCnf
      - DOCKER_INFLUXDB_INIT_BUCKET=labBucket
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXD_TLS_CERT=/etc/ssl/influxdb.pem
      - INFLUXD_TLS_KEY=/etc/ssl/influxdb.key
  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana/local.yml:/etc/grafana/provisioning/dashboards/local.yml
      - ./ssl/private.key:/etc/grafana/private.key
      - ./ssl/certificate.crt:/etc/grafana/certificate.crt
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      GF_SECURITY_ADMIN_USER: 'grafana'
      GF_SECURITY_ADMIN_PASSWORD: 'ChangePassword'
      VIRTUAL_HOST: 'localhost'
      VIRTUAL_PROTO: 'https'
      VIRTUAL_PORT: '3000'
      GF_SERVER_CERT_FILE: '/etc/grafana/certificate.crt'
      GF_SERVER_CERT_KEY: '/etc/grafana/private.key'
      GF_SERVER_PROTOCOL: 'https'
      GF_INSTALL_PLUGINS: 'grafana-piechart-panel,grafana-worldmap-panel'
      GF_SERVER_DOMAIN: 'localhost.local'